#############################################################################
# Makefile for building: IntervalGenetic
# Generated by qmake (3.1) (Qt 5.15.17)
# Project:  IntervalGenetic.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile IntervalGenetic.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -O3 -march=native -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -fopt-info-optimized-vec-loop-omp -O2 -O3 -march=native -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -fopt-info-optimized-vec-loop-omp -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O3 -march=native -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -fopt-info-optimized-vec-loop-omp -O2 -O3 -march=native -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -fopt-info-optimized-vec-loop-omp -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I. -I/../lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = IntervalGenetic1.0.0
DISTDIR = /home/sheridan/Desktop/ERGASIES/IntervalGenetic/.tmp/IntervalGenetic1.0.0
LINK          = g++
LFLAGS        = -O3 -Wl,-O1
LIBS          = $(SUBLIBS) -lm -fopenmp /usr/lib64/libQt5Core.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = boundedgradientdescent.cpp \
		constrainedadam.cpp \
		dllproblem.cpp \
		doublepop.cpp \
		getoptions.cpp \
		GE/grammargenetic.cpp \
		GE/integeranneal.cpp \
		GE/symbol.cc \
		GE/doublestack.cc \
		GE/fparser.cc \
		GE/fpoptimizer.cc \
		GE/program.cc \
		GE/rule.cc \
		GE/cprogram.cc \
		integergenetic.cpp \
		interval.cpp \
		intervalgenetic.cpp \
		intervalproblem.cpp \
		intervalpso.cpp \
		main.cpp \
		simanbounds.cpp \
		tolmin.cc \
		problem.cpp 
OBJECTS       = boundedgradientdescent.o \
		constrainedadam.o \
		dllproblem.o \
		doublepop.o \
		getoptions.o \
		grammargenetic.o \
		integeranneal.o \
		symbol.o \
		doublestack.o \
		fparser.o \
		fpoptimizer.o \
		program.o \
		rule.o \
		cprogram.o \
		integergenetic.o \
		interval.o \
		intervalgenetic.o \
		intervalproblem.o \
		intervalpso.o \
		main.o \
		simanbounds.o \
		tolmin.o \
		problem.o
DIST          = /../lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/../lib64/qt5/mkspecs/qconfig.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/../lib64/qt5/mkspecs/features/qt_functions.prf \
		/../lib64/qt5/mkspecs/features/qt_config.prf \
		/../lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/../lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/../lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/../lib64/qt5/mkspecs/features/toolchain.prf \
		/../lib64/qt5/mkspecs/features/default_pre.prf \
		/../lib64/qt5/mkspecs/features/resolve_config.prf \
		/../lib64/qt5/mkspecs/features/default_post.prf \
		/../lib64/qt5/mkspecs/features/warn_on.prf \
		/../lib64/qt5/mkspecs/features/qt.prf \
		/../lib64/qt5/mkspecs/features/resources_functions.prf \
		/../lib64/qt5/mkspecs/features/resources.prf \
		/../lib64/qt5/mkspecs/features/moc.prf \
		/../lib64/qt5/mkspecs/features/unix/thread.prf \
		/../lib64/qt5/mkspecs/features/qmake_use.prf \
		/../lib64/qt5/mkspecs/features/file_copies.prf \
		/../lib64/qt5/mkspecs/features/testcase_targets.prf \
		/../lib64/qt5/mkspecs/features/exceptions.prf \
		/../lib64/qt5/mkspecs/features/yacc.prf \
		/../lib64/qt5/mkspecs/features/lex.prf \
		IntervalGenetic.pro boundedgradientdescent.h \
		constrainedadam.h \
		dllproblem.h \
		doublepop.h \
		getoptions.h \
		GE/grammargenetic.h \
		GE/integeranneal.h \
		GE/symbol.h \
		GE/doublestack.h \
		GE/fparser.hh \
		GE/fpconfig.hh \
		GE/fptypes.hh \
		GE/program.h \
		GE/rule.h \
		GE/cprogram.h \
		integergenetic.h \
		interval.h \
		intervalgenetic.h \
		intervalproblem.h \
		intervalpso.h \
		simanbounds.h \
		tolmin.h \
		problem.h boundedgradientdescent.cpp \
		constrainedadam.cpp \
		dllproblem.cpp \
		doublepop.cpp \
		getoptions.cpp \
		GE/grammargenetic.cpp \
		GE/integeranneal.cpp \
		GE/symbol.cc \
		GE/doublestack.cc \
		GE/fparser.cc \
		GE/fpoptimizer.cc \
		GE/program.cc \
		GE/rule.cc \
		GE/cprogram.cc \
		integergenetic.cpp \
		interval.cpp \
		intervalgenetic.cpp \
		intervalproblem.cpp \
		intervalpso.cpp \
		main.cpp \
		simanbounds.cpp \
		tolmin.cc \
		problem.cpp
QMAKE_TARGET  = IntervalGenetic
DESTDIR       = 
TARGET        = IntervalGenetic


first: all
####### Build rules

IntervalGenetic:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: IntervalGenetic.pro /../lib64/qt5/mkspecs/linux-g++/qmake.conf /../lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/../lib64/qt5/mkspecs/qconfig.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/../lib64/qt5/mkspecs/features/qt_functions.prf \
		/../lib64/qt5/mkspecs/features/qt_config.prf \
		/../lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/../lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/../lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/../lib64/qt5/mkspecs/features/toolchain.prf \
		/../lib64/qt5/mkspecs/features/default_pre.prf \
		/../lib64/qt5/mkspecs/features/resolve_config.prf \
		/../lib64/qt5/mkspecs/features/default_post.prf \
		/../lib64/qt5/mkspecs/features/warn_on.prf \
		/../lib64/qt5/mkspecs/features/qt.prf \
		/../lib64/qt5/mkspecs/features/resources_functions.prf \
		/../lib64/qt5/mkspecs/features/resources.prf \
		/../lib64/qt5/mkspecs/features/moc.prf \
		/../lib64/qt5/mkspecs/features/unix/thread.prf \
		/../lib64/qt5/mkspecs/features/qmake_use.prf \
		/../lib64/qt5/mkspecs/features/file_copies.prf \
		/../lib64/qt5/mkspecs/features/testcase_targets.prf \
		/../lib64/qt5/mkspecs/features/exceptions.prf \
		/../lib64/qt5/mkspecs/features/yacc.prf \
		/../lib64/qt5/mkspecs/features/lex.prf \
		IntervalGenetic.pro
	$(QMAKE) -o Makefile IntervalGenetic.pro
/../lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/../lib64/qt5/mkspecs/qconfig.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_nfc.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/../lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/../lib64/qt5/mkspecs/features/qt_functions.prf:
/../lib64/qt5/mkspecs/features/qt_config.prf:
/../lib64/qt5/mkspecs/linux-g++/qmake.conf:
/../lib64/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/../lib64/qt5/mkspecs/features/exclusive_builds.prf:
/../lib64/qt5/mkspecs/features/toolchain.prf:
/../lib64/qt5/mkspecs/features/default_pre.prf:
/../lib64/qt5/mkspecs/features/resolve_config.prf:
/../lib64/qt5/mkspecs/features/default_post.prf:
/../lib64/qt5/mkspecs/features/warn_on.prf:
/../lib64/qt5/mkspecs/features/qt.prf:
/../lib64/qt5/mkspecs/features/resources_functions.prf:
/../lib64/qt5/mkspecs/features/resources.prf:
/../lib64/qt5/mkspecs/features/moc.prf:
/../lib64/qt5/mkspecs/features/unix/thread.prf:
/../lib64/qt5/mkspecs/features/qmake_use.prf:
/../lib64/qt5/mkspecs/features/file_copies.prf:
/../lib64/qt5/mkspecs/features/testcase_targets.prf:
/../lib64/qt5/mkspecs/features/exceptions.prf:
/../lib64/qt5/mkspecs/features/yacc.prf:
/../lib64/qt5/mkspecs/features/lex.prf:
IntervalGenetic.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile IntervalGenetic.pro

qmake_all: FORCE


all: Makefile IntervalGenetic

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /../lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents boundedgradientdescent.h constrainedadam.h dllproblem.h doublepop.h getoptions.h GE/grammargenetic.h GE/integeranneal.h GE/symbol.h GE/doublestack.h GE/fparser.hh GE/fpconfig.hh GE/fptypes.hh GE/program.h GE/rule.h GE/cprogram.h integergenetic.h interval.h intervalgenetic.h intervalproblem.h intervalpso.h simanbounds.h tolmin.h problem.h $(DISTDIR)/
	$(COPY_FILE) --parents boundedgradientdescent.cpp constrainedadam.cpp dllproblem.cpp doublepop.cpp getoptions.cpp GE/grammargenetic.cpp GE/integeranneal.cpp GE/symbol.cc GE/doublestack.cc GE/fparser.cc GE/fpoptimizer.cc GE/program.cc GE/rule.cc GE/cprogram.cc integergenetic.cpp interval.cpp intervalgenetic.cpp intervalproblem.cpp intervalpso.cpp main.cpp simanbounds.cpp tolmin.cc problem.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /../lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O3 -march=native -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -fopt-info-optimized-vec-loop-omp -O2 -O3 -march=native -fopenmp -unroll-loops -omit-frame-pointer -Winline -unsafe-math-optimizations -mtune=native -pthread -fopt-info-optimized-vec-loop-omp -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /../lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

boundedgradientdescent.o: boundedgradientdescent.cpp boundedgradientdescent.h \
		problem.h \
		intervalproblem.h \
		interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o boundedgradientdescent.o boundedgradientdescent.cpp

constrainedadam.o: constrainedadam.cpp constrainedadam.h \
		problem.h \
		intervalproblem.h \
		interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o constrainedadam.o constrainedadam.cpp

dllproblem.o: dllproblem.cpp dllproblem.h \
		intervalproblem.h \
		interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dllproblem.o dllproblem.cpp

doublepop.o: doublepop.cpp doublepop.h \
		problem.h \
		intervalproblem.h \
		interval.h \
		tolmin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doublepop.o doublepop.cpp

getoptions.o: getoptions.cpp getoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o getoptions.o getoptions.cpp

grammargenetic.o: GE/grammargenetic.cpp GE/grammargenetic.h \
		intervalproblem.h \
		interval.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		GE/integeranneal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grammargenetic.o GE/grammargenetic.cpp

integeranneal.o: GE/integeranneal.cpp GE/integeranneal.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		interval.h \
		intervalproblem.h \
		GE/grammargenetic.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integeranneal.o GE/integeranneal.cpp

symbol.o: GE/symbol.cc GE/symbol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o symbol.o GE/symbol.cc

doublestack.o: GE/doublestack.cc GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o doublestack.o GE/doublestack.cc

fparser.o: GE/fparser.cc GE/fparser.hh \
		GE/fpconfig.hh \
		GE/fptypes.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fparser.o GE/fparser.cc

fpoptimizer.o: GE/fpoptimizer.cc GE/fpconfig.hh \
		GE/fparser.hh \
		GE/fptypes.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fpoptimizer.o GE/fpoptimizer.cc

program.o: GE/program.cc GE/program.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o program.o GE/program.cc

rule.o: GE/rule.cc GE/rule.h \
		GE/symbol.h \
		GE/doublestack.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rule.o GE/rule.cc

cprogram.o: GE/cprogram.cc GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cprogram.o GE/cprogram.cc

integergenetic.o: integergenetic.cpp integergenetic.h \
		intervalproblem.h \
		interval.h \
		tolmin.h \
		problem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integergenetic.o integergenetic.cpp

interval.o: interval.cpp interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interval.o interval.cpp

intervalgenetic.o: intervalgenetic.cpp intervalgenetic.h \
		intervalproblem.h \
		interval.h \
		problem.h \
		tolmin.h \
		dllproblem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o intervalgenetic.o intervalgenetic.cpp

intervalproblem.o: intervalproblem.cpp intervalproblem.h \
		interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o intervalproblem.o intervalproblem.cpp

intervalpso.o: intervalpso.cpp intervalpso.h \
		intervalproblem.h \
		interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o intervalpso.o intervalpso.cpp

main.o: main.cpp intervalproblem.h \
		interval.h \
		dllproblem.h \
		getoptions.h \
		intervalpso.h \
		intervalgenetic.h \
		tolmin.h \
		problem.h \
		doublepop.h \
		integergenetic.h \
		constrainedadam.h \
		boundedgradientdescent.h \
		GE/grammargenetic.h \
		GE/cprogram.h \
		GE/symbol.h \
		GE/rule.h \
		GE/doublestack.h \
		GE/fparser.hh \
		simanbounds.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

simanbounds.o: simanbounds.cpp simanbounds.h \
		intervalproblem.h \
		interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simanbounds.o simanbounds.cpp

tolmin.o: tolmin.cc tolmin.h \
		problem.h \
		intervalproblem.h \
		interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tolmin.o tolmin.cc

problem.o: problem.cpp problem.h \
		intervalproblem.h \
		interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o problem.o problem.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/IntervalGenetic/bin || mkdir -p $(INSTALL_ROOT)/opt/IntervalGenetic/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/IntervalGenetic/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/IntervalGenetic/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/IntervalGenetic/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/IntervalGenetic/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

